### PR TITLE
Implemented separate Responsive Contact us form : Issue no #18

### PR DESCRIPTION
**Pull request by AbhijitMotekar99**
### Before

Screenshot 2024-10-04 154002

### After
Wordweave contact us

### Responsive
Wordweave contact us responsive

### CODE REVIEW

**Comment by AbhijitMotekar99** [comment]
Hey @Manishkr1007 
I have created a separate "Contact Us" form with a color combination that matches the overall website, and I have also made it responsive. Please add a **Level 3 label**; I kindly request this.

also add **gssoc-ext** label,

**Comment by AbhijitMotekar99** [comment]
Hey @Manishkr1007 
Plz merge the pr.

**Comment by AbhijitMotekar99** [comment]
Hey @Manishkr1007 @sanjay-kv @devxMani

**Comment by AbhijitMotekar99** [comment]
Please merge my PR

**Comment by Manishkr1007** [comment]
hey you just work on the ui and make it more attractive after that i will assign it level 2 for now it is level 1

**Comment by devxMani** [comment]
@AbhijitMotekar99 @Manishkr1007 bro unhe mat tag kar woh nhi kra rhe merge sanjay kv 😂

**Comment by AbhijitMotekar99** [comment]
Hey @Manishkr1007 
Please add labels gssoc-ext and level

**Pull request merged**
